// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxScsK31ebmcyQu6bmugHU0mrUC2nA-pI',
    appId: '1:26245276297:web:61dfb5c8c312a7d7975c58',
    messagingSenderId: '26245276297',
    projectId: 'flutter-chat-app-6559f',
    authDomain: 'flutter-chat-app-6559f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-6559f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs2Oj9kR-QZL9N7ddE5Fbv0tatk1pHewY',
    appId: '1:26245276297:android:bd35184b0233f2ec975c58',
    messagingSenderId: '26245276297',
    projectId: 'flutter-chat-app-6559f',
    storageBucket: 'flutter-chat-app-6559f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd5jxwOlzLE_CdICsXhMkeHc6w7Ketsm4',
    appId: '1:26245276297:ios:65dce664616a88dd975c58',
    messagingSenderId: '26245276297',
    projectId: 'flutter-chat-app-6559f',
    storageBucket: 'flutter-chat-app-6559f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
